/**
 * Prepared route-scoped event dataset contract — Stage 2 / Issue #93
 *
 * Defines the shape of a prepared route-scoped event dataset file
 * (e.g. Rostov1.events.json). This file is generated by the local
 * prepareRouteEvents.mjs script from raw OpenSpeedcam/Datakam CSV data
 * and is consumed at runtime by the emulator when a route is selected.
 *
 * EMULATOR OPERATOR / QA USE ONLY — NOT THE DRIVER-FACING UI.
 * NOT Product Canon.
 *
 * Product data policy:
 *   - Raw OpenSpeedcam/Datakam source files must NOT be committed.
 *   - Prepared bounded route-scoped output MAY be committed when generated
 *     for emulator use and explicitly approved.
 *   - source.raw_source_committed must always be false.
 *
 * Canon authority: docs/product/areas/event-data/event-data.md
 *
 * WIP — field names and shape are subject to revision.
 */

/**
 * Normalized event type for route-scoped prepared events.
 *
 * Includes "unknown" for raw TYPE codes that could not be confidently mapped.
 * Unknown events are preserved in the dataset — they are not silently dropped.
 *
 * WIP — not Product Canon. The mapping is conservative and subject to revision.
 */
export type RouteEventNormalizedType =
  | "speed_limit"
  | "static_camera"
  | "road_bump"
  | "unknown";

/** Source metadata block describing where the raw data came from. */
export interface RouteEventDatasetSource {
  /**
   * Kind identifier for the preparation pipeline.
   * Must be "openspeedcam_datakam_prepared" for datasets generated by
   * prepareRouteEvents.mjs.
   */
  kind: string;

  /**
   * Must be false — raw source files must not be committed.
   * If true, the dataset is invalid and must be rejected.
   */
  raw_source_committed: false;

  /** Description of the raw source format (informational). */
  raw_format: string;
}

/** Corridor geometry used during route-scoped extraction. */
export interface RouteEventDatasetCorridor {
  /** Buffer around the route in metres used to filter candidate events. */
  buffer_m: number;
}

/** Summary counts from the preparation run. */
export interface RouteEventDatasetSummary {
  /** Total raw rows read from the CSV input. */
  raw_rows_scanned: number;

  /** Number of events retained in the prepared output. */
  selected_events: number;

  /** Number of raw rows skipped due to parse/validation errors. */
  skipped_invalid: number;

  /** Number of valid rows skipped because they fell outside the corridor. */
  skipped_outside_corridor: number;

  /** Breakdown of retained events by normalized type. */
  by_type: {
    speed_limit: number;
    static_camera: number;
    road_bump: number;
    unknown: number;
  };
}

/**
 * A single prepared route-scoped event.
 *
 * Preserves source provenance, raw fields, and adds route-relative geometry.
 * All events are candidate observations — not verified RoadAhead truth.
 *
 * Canon constraints:
 *   - Events are candidate observations, not verified truth (event-data truth 1, 5).
 *   - Source provenance is preserved (event-data truth 8).
 *   - Unknown raw TYPE values are preserved as type "unknown" — not dropped.
 *   - No legal speed-limit authority is claimed.
 */
export interface RouteEvent {
  /**
   * Stable identifier for this prepared event.
   * Format: "osc_<IDX>" (e.g. "osc_177") for OpenSpeedcam/Datakam sources.
   */
  id: string;

  /** Raw IDX value from the source CSV row (as string for cross-reference). */
  source_ref: string;

  /** Source dataset identifier — "openspeedcam_datakam" for OSC/Datakam files. */
  source: string;

  /**
   * Raw TYPE integer from the source CSV row.
   * Preserved for provenance and debugging — do not discard.
   */
  raw_type: number;

  /**
   * Normalized event type derived from raw_type via the WIP type mapping layer.
   * "unknown" when raw_type could not be confidently mapped.
   * WIP — not Product Canon.
   */
  type: RouteEventNormalizedType;

  /** WGS84 longitude (X field in OpenSpeedcam CSV). Longitude-first convention. */
  lon: number;

  /** WGS84 latitude (Y field in OpenSpeedcam CSV). */
  lat: number;

  /**
   * Advisory speed value in km/h from the source SPEED field.
   * Null if not applicable (SPEED is 0 or absent for this event type).
   * Advisory guidance context only — not a legal speed-limit authority.
   * (speed-reference Canon truths 4, 5; event-data Canon truths 1, 5)
   */
  speed_kmh: number | null;

  /**
   * Raw DIRTYPE value from the source CSV.
   * Direction type applicability: 0 = all directions, 1 = one direction,
   * 2 = both directions. WIP — semantics are not Canon.
   */
  dirtype: number;

  /**
   * Raw DIRECTION value in degrees from the source CSV.
   * Candidate bearing signal — semantics are WIP and not Canon.
   * (event-applicability Canon truth 8)
   */
  direction_deg: number;

  /**
   * Perpendicular distance from this event's position to the nearest point
   * on the route polyline, in metres. Computed during extraction.
   * Per-session derived — not Product Canon.
   */
  distance_to_route_m: number;

  /**
   * Along-route distance (arc-length from route start) to the nearest projected
   * point on the route polyline, in metres. Computed during extraction.
   * Per-session derived — not Product Canon.
   */
  projected_route_distance_m: number;
}

/** The top-level prepared route-scoped event dataset document. */
export interface RouteEventDataset {
  /** Schema version — must be 1 for this contract revision. */
  schema_version: 1;

  /**
   * Route identifier — must match the registry route id that loaded this dataset.
   * Validated at load time; mismatch causes a dataset validation error.
   */
  route_id: string;

  /** ISO 8601 timestamp of when this dataset was generated. */
  generated_at: string;

  /** Source metadata. */
  source: RouteEventDatasetSource;

  /** Corridor geometry used during extraction. */
  corridor: RouteEventDatasetCorridor;

  /** Summary counts from the preparation run. */
  summary: RouteEventDatasetSummary;

  /** Prepared route-scoped events. */
  events: RouteEvent[];
}

// ---------------------------------------------------------------------------
// Runtime parser / validator
// ---------------------------------------------------------------------------

/**
 * Parse and validate raw JSON as a RouteEventDataset.
 *
 * Validation rules (per issue #93 spec):
 *   - schema_version must be 1
 *   - route_id must be a non-empty string; caller should verify it matches
 *     the selected route id via validateRouteEventDatasetRouteId()
 *   - source.raw_source_committed must be false
 *   - events must be an array
 *   - each event must preserve required fields
 *
 * Throws a descriptive Error on validation failure.
 * Returns a typed RouteEventDataset on success.
 *
 * WIP — NOT Product Canon. Stage 2 / Issue #93.
 */
export function parseRouteEventDataset(raw: unknown): RouteEventDataset {
  if (typeof raw !== "object" || raw === null) {
    throw new Error("Route event dataset: expected a JSON object");
  }
  const obj = raw as Record<string, unknown>;

  if (obj["schema_version"] !== 1) {
    throw new Error(
      `Route event dataset: schema_version must be 1, got ${String(obj["schema_version"])}`
    );
  }

  const routeId = obj["route_id"];
  if (typeof routeId !== "string" || routeId.trim() === "") {
    throw new Error(
      "Route event dataset: route_id must be a non-empty string"
    );
  }

  const generatedAt = obj["generated_at"];
  if (typeof generatedAt !== "string") {
    throw new Error("Route event dataset: generated_at must be a string");
  }

  const rawSource = obj["source"];
  if (typeof rawSource !== "object" || rawSource === null) {
    throw new Error("Route event dataset: source must be an object");
  }
  const sourceObj = rawSource as Record<string, unknown>;

  if (sourceObj["raw_source_committed"] !== false) {
    throw new Error(
      "Route event dataset: source.raw_source_committed must be false — " +
        "raw OpenSpeedcam/Datakam files must not be committed"
    );
  }
  const sourceKind = sourceObj["kind"];
  if (typeof sourceKind !== "string" || sourceKind.trim() === "") {
    throw new Error(
      "Route event dataset: source.kind must be a non-empty string"
    );
  }
  const rawFormat = sourceObj["raw_format"];
  const source: RouteEventDatasetSource = {
    kind: sourceKind,
    raw_source_committed: false,
    raw_format: typeof rawFormat === "string" ? rawFormat : "",
  };

  const rawCorridor = obj["corridor"];
  if (typeof rawCorridor !== "object" || rawCorridor === null) {
    throw new Error("Route event dataset: corridor must be an object");
  }
  const corridorObj = rawCorridor as Record<string, unknown>;
  const bufferM = corridorObj["buffer_m"];
  if (typeof bufferM !== "number" || !isFinite(bufferM) || bufferM <= 0) {
    throw new Error(
      `Route event dataset: corridor.buffer_m must be a positive number, got ${String(bufferM)}`
    );
  }
  const corridor: RouteEventDatasetCorridor = { buffer_m: bufferM };

  const rawSummary = obj["summary"];
  if (typeof rawSummary !== "object" || rawSummary === null) {
    throw new Error("Route event dataset: summary must be an object");
  }
  const summaryObj = rawSummary as Record<string, unknown>;

  /** Validate a summary count field: finite number >= 0. */
  function requireSummaryCount(field: string, value: unknown): number {
    if (typeof value !== "number" || !isFinite(value) || value < 0) {
      throw new Error(
        `Route event dataset: summary.${field} must be a finite number >= 0, got ${String(value)}`
      );
    }
    return value;
  }

  const rawByType = summaryObj["by_type"];
  if (typeof rawByType !== "object" || rawByType === null) {
    throw new Error("Route event dataset: summary.by_type must be an object");
  }
  const bt = rawByType as Record<string, unknown>;

  const summary: RouteEventDatasetSummary = {
    raw_rows_scanned: requireSummaryCount(
      "raw_rows_scanned",
      summaryObj["raw_rows_scanned"]
    ),
    selected_events: requireSummaryCount(
      "selected_events",
      summaryObj["selected_events"]
    ),
    skipped_invalid: requireSummaryCount(
      "skipped_invalid",
      summaryObj["skipped_invalid"]
    ),
    skipped_outside_corridor: requireSummaryCount(
      "skipped_outside_corridor",
      summaryObj["skipped_outside_corridor"]
    ),
    by_type: {
      speed_limit: requireSummaryCount("by_type.speed_limit", bt["speed_limit"]),
      static_camera: requireSummaryCount(
        "by_type.static_camera",
        bt["static_camera"]
      ),
      road_bump: requireSummaryCount("by_type.road_bump", bt["road_bump"]),
      unknown: requireSummaryCount("by_type.unknown", bt["unknown"]),
    },
  };

  const rawEvents = obj["events"];
  if (!Array.isArray(rawEvents)) {
    throw new Error("Route event dataset: events must be an array");
  }

  const events: RouteEvent[] = rawEvents.map(
    (ev: unknown, i: number): RouteEvent => {
      if (typeof ev !== "object" || ev === null) {
        throw new Error(
          `Route event dataset events[${i}]: expected an object`
        );
      }
      const e = ev as Record<string, unknown>;

      const id = e["id"];
      if (typeof id !== "string" || id.trim() === "") {
        throw new Error(
          `Route event dataset events[${i}]: id must be a non-empty string`
        );
      }

      const sourceRef = e["source_ref"];
      if (typeof sourceRef !== "string") {
        throw new Error(
          `Route event dataset events[${i}] (id="${id}"): source_ref must be a string`
        );
      }

      const evSource = e["source"];
      if (typeof evSource !== "string") {
        throw new Error(
          `Route event dataset events[${i}] (id="${id}"): source must be a string`
        );
      }

      const tag = `Route event dataset events[${i}] (id="${id}")`;

      const rawType = e["raw_type"];
      if (typeof rawType !== "number" || !isFinite(rawType)) {
        throw new Error(`${tag}: raw_type must be a finite number`);
      }

      const type = e["type"];
      if (
        type !== "speed_limit" &&
        type !== "static_camera" &&
        type !== "road_bump" &&
        type !== "unknown"
      ) {
        throw new Error(
          `${tag}: type must be one of ` +
            `speed_limit | static_camera | road_bump | unknown, got "${String(type)}"`
        );
      }

      const lon = e["lon"];
      if (typeof lon !== "number" || !isFinite(lon)) {
        throw new Error(`${tag}: lon must be a finite number`);
      }
      if (lon < -180 || lon > 180) {
        throw new Error(`${tag}: lon out of range [-180, 180]: ${lon}`);
      }

      const lat = e["lat"];
      if (typeof lat !== "number" || !isFinite(lat)) {
        throw new Error(`${tag}: lat must be a finite number`);
      }
      if (lat < -90 || lat > 90) {
        throw new Error(`${tag}: lat out of range [-90, 90]: ${lat}`);
      }

      // speed_kmh: null or a finite positive number.
      const rawSpeedKmh = e["speed_kmh"];
      let speedKmh: number | null;
      if (rawSpeedKmh === null || rawSpeedKmh === undefined) {
        speedKmh = null;
      } else if (typeof rawSpeedKmh !== "number" || !isFinite(rawSpeedKmh)) {
        throw new Error(
          `${tag}: speed_kmh must be null or a finite number, got ${String(rawSpeedKmh)}`
        );
      } else if (rawSpeedKmh <= 0) {
        throw new Error(
          `${tag}: speed_kmh must be positive when present, got ${rawSpeedKmh}`
        );
      } else {
        speedKmh = rawSpeedKmh;
      }

      // dirtype: finite integer.
      const rawDirtype = e["dirtype"];
      if (typeof rawDirtype !== "number" || !isFinite(rawDirtype)) {
        throw new Error(
          `${tag}: dirtype must be a finite number, got ${String(rawDirtype)}`
        );
      }

      // direction_deg: finite, 0 <= direction_deg <= 360.
      // 360 is accepted (equal to 0 / north) to match source data conventions.
      const rawDirectionDeg = e["direction_deg"];
      if (typeof rawDirectionDeg !== "number" || !isFinite(rawDirectionDeg)) {
        throw new Error(
          `${tag}: direction_deg must be a finite number, got ${String(rawDirectionDeg)}`
        );
      }
      if (rawDirectionDeg < 0 || rawDirectionDeg > 360) {
        throw new Error(
          `${tag}: direction_deg out of range [0, 360]: ${rawDirectionDeg}`
        );
      }

      // distance_to_route_m: finite, >= 0.
      const rawDistanceToRouteM = e["distance_to_route_m"];
      if (
        typeof rawDistanceToRouteM !== "number" ||
        !isFinite(rawDistanceToRouteM) ||
        rawDistanceToRouteM < 0
      ) {
        throw new Error(
          `${tag}: distance_to_route_m must be a finite number >= 0, got ${String(rawDistanceToRouteM)}`
        );
      }

      // projected_route_distance_m: finite, >= 0.
      const rawProjectedRouteDistanceM = e["projected_route_distance_m"];
      if (
        typeof rawProjectedRouteDistanceM !== "number" ||
        !isFinite(rawProjectedRouteDistanceM) ||
        rawProjectedRouteDistanceM < 0
      ) {
        throw new Error(
          `${tag}: projected_route_distance_m must be a finite number >= 0, got ${String(rawProjectedRouteDistanceM)}`
        );
      }

      return {
        id,
        source_ref: sourceRef,
        source: evSource,
        raw_type: rawType,
        type: type as RouteEventNormalizedType,
        lon,
        lat,
        speed_kmh: speedKmh,
        dirtype: rawDirtype,
        direction_deg: rawDirectionDeg,
        distance_to_route_m: rawDistanceToRouteM,
        projected_route_distance_m: rawProjectedRouteDistanceM,
      };
    }
  );

  return {
    schema_version: 1,
    route_id: routeId,
    generated_at: generatedAt,
    source,
    corridor,
    summary,
    events,
  };
}

/**
 * Validate that a parsed RouteEventDataset's route_id matches the expected
 * route id from the registry selection.
 *
 * Called after parseRouteEventDataset() succeeds — as a separate step so
 * the parse error and id-mismatch error can be distinguished.
 *
 * Throws a descriptive Error on mismatch.
 */
export function validateRouteEventDatasetRouteId(
  dataset: RouteEventDataset,
  expectedRouteId: string
): void {
  if (dataset.route_id !== expectedRouteId) {
    throw new Error(
      `Route event dataset: route_id mismatch — ` +
        `dataset says "${dataset.route_id}", selected route is "${expectedRouteId}"`
    );
  }
}
